name: Lint and Comment on PR

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run lint
      continue-on-error: true
      id: lint

    - name: Create status output
      id: status
      run: |
        if [ ${{ steps.lint.outcome }} == 'success' ]; then
          echo "status=success" >> $GITHUB_ENV
        else
          echo "status=failure" >> $GITHUB_ENV
        fi

    - name: Set GitHub status check
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const state = process.env.status === 'success' ? 'success' : 'failure';
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.pull_request.head.sha,
            state: state,
            context: 'build',
            description: state === 'success' ? 'Build successful' : 'Build failed'
          });

    - name: Post success comment
      if: ${{ env.status == 'success' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: "The build was successful! :white_check_mark::white_check_mark:"
          })

    - name: Post failure comment
      if: ${{ env.status == 'failure' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: "The build failed. :poop::poop:"
          })