name: Buld and Comment on PR

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build-all
      continue-on-error: true
      id: lint

    - name: Create status output
      id: status
      run: |
        if [ ${{ steps.lint.outcome }} == 'success' ]; then
          echo "status=success" >> $GITHUB_ENV
        else
          echo "status=failure" >> $GITHUB_ENV
        fi

    - name: Set GitHub status check
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const state = process.env.status === 'success' ? 'success' : 'failure';
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.pull_request.head.sha,
            state: state,
            context: 'build',
            description: state === 'success' ? 'Build successful' : 'Build failed'
          });

    - name: Post success comment
      if: ${{ env.status == 'success' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `![success](https://github.com/luongdinhkhanhvinh/main-micro-order/assets/57809324/99b62b8d-5869-46f9-b3e5-75e65cc5c160)
                    The build was successful! :white_check_mark::white_check_mark:`
          })

    - name: Post failure comment
      if: ${{ env.status == 'failure' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `![error](https://github.com/luongdinhkhanhvinh/main-micro-order/assets/57809324/3b22b98b-6b5a-4a35-928c-c8a88df7463b)
                    The build failed. :poop::poop:`
          })
